name: PR Merge Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-python-code:
    runs-on: self-hosted
    steps:
      - name: test log
        run: echo "python code start"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python test.py